import {
  ArrowRight,
  CheckCircle2,
  Copy,
  Download,
  QrCode,
  Stethoscope,
} from 'lucide-react'

function DoctorCode({ onNavigate }) {
  const doctorCode = 'VAN-ABC123'

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(doctorCode)
    } catch {
      // Clipboard access may be unavailable in some browsers.
    }
  }

  const handleDownloadQR = () => {
    // The QR graphic is currently a UI placeholder.
    // Real QR download will be connected when the backend
    // provides the generated doctor QR.
  }

  return (
    <div className="auth-page doctor-code-page">
      <div className="doctor-code-card">
        <div className="auth-brand">
          <div className="auth-brand-icon">
            <Stethoscope size={25} strokeWidth={2.2} />
          </div>

          <div>
            <h1>VaaniDoc</h1>
            <span>Doctor Dashboard</span>
          </div>
        </div>

        <div className="doctor-code-heading">
          <div className="success-icon">
            <CheckCircle2 size={28} />
          </div>

          <span className="eyebrow">ACCOUNT CREATED</span>

          <h2>Your consultation code is ready</h2>

          <p>
            Patients can scan your QR code or enter your doctor code to
            join your consultation queue.
          </p>
        </div>

        <div className="qr-placeholder">
          <QrCode size={150} strokeWidth={1.4} />

          <span>Doctor QR Code</span>
          <small>Generated by VaaniDoc</small>
        </div>

        <button
          type="button"
          className="download-qr-button"
          onClick={handleDownloadQR}
        >
          <Download size={17} />
          Download QR
        </button>

        <div className="doctor-code-section">
          <span className="doctor-code-label">
            YOUR DOCTOR CODE
          </span>

          <div className="doctor-code-value">
            <strong>{doctorCode}</strong>

            <button
              type="button"
              className="copy-code-button"
              onClick={handleCopy}
              aria-label="Copy doctor code"
              title="Copy doctor code"
            >
              <Copy size={17} />
            </button>
          </div>
        </div>

        <div className="doctor-code-note">
          <strong>Keep this code accessible</strong>
          <p>
            This code identifies you as the selected doctor. It does not
            contain patient information.
          </p>
        </div>

        <button
          type="button"
          className="auth-primary-button"
          onClick={() => onNavigate('dashboard')}
        >
          Continue to Dashboard
          <ArrowRight size={17} />
        </button>

        <p className="auth-privacy">
          Doctor QR and code are for connecting patients to your
          consultation queue.
        </p>
      </div>
    </div>
  )
}

export default DoctorCode